"""Initial migration.

Revision ID: 5672ab8831d7
Revises: 6361b7ca3e7e
Create Date: 2024-06-09 19:56:00.265177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5672ab8831d7'
down_revision = '6361b7ca3e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('miles_smiles_member')
    op.drop_table('flight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=50), nullable=True),
    sa.Column('destination', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miles_smiles_member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('miles_points', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('passenger_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('passenger_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('miles_member_id', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
